global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fastapi-project'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'fastapi-backend'
    static_configs:
      - targets: ['fastapi-project:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9188']
    scrape_interval: 10s

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 10s

